### ISSUE TITLE
Comments from another user not visible on Safari, requiring more than a simple refresh to recover them.

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#325] opened 2016-01-29 21:45 UTC
arpaddanos recently submitted new coordinates for a variant (see page below). He noticed that Malachi had commented on them but when he looked at the page on Safari, the comments weren't there. A simple refresh did not fix the problem. They were visible on my computer, regardless of browser. He could view them in Firefox but the only fix for Safari seemed to be to use the "clear web data" option in his safari preferences. 

https://civic.genome.wustl.edu/#/events/genes/20/summary/variants/413/talk/revisions/list/726/summary#variant

**Comment by jmcmichael** [comment] 2016-02-11 18:09
It looks like [Safari caches XHR calls](http://www.raymondcamden.com/2015/07/16/safari-and-http-caching/), unlike the other browsers. After a bit of research, it appears that there exist a couple of work-arounds. Safari pays attention to { cache:false } attribute in the XHR request, and will not cache those responses. Also, it pays attention to Cache-Control: no-cache headers sent from the server.

I'll discuss with Adam how to best implement the fix for this.

**Comment by jmcmichael** [comment] 2016-02-12 19:38
I was unable to reproduce this on the current master. To test, I did the following:

1) Using Safari I navigated to a variant view, and hit the 'Edit Coordinates' button, typed in a few coordinates, hit Submit, and then View Now.
2) I then logged in as a different user on Chrome, navigated to the new revision detail page, and entered a comment.
3) Hit reload in Safari.

When I did this, Safari displayed the new comment from the other user, as expected. I believe this simulates the same sequence of actions that arpaddanos executed. I double checked, and the comments cache is definitely being cleared after a new comment is submitted. So I'm not sure what is going on here.

@kkrysiak, I'm going to close this issue, but the next time you've commented on a variant revision on the live site, could you open up the same page in Safari and verify that your new comment appears after a normal refresh? Then we'll see if this is just happening on the live site for some reason - and please reopen this issue if that is the case.

**Closed by jmcmichael** 2016-02-12 19:38 UTC
Labels: high priority, in progress

**Comment by kkrysiak** [comment] 2016-02-12 19:53
@arpaddanos notified me of the error. I'm tagging him here so if it comes up again he can reopen the issue.
