### ISSUE TITLE
Quick search isn't always working

### ISSUE THREAD

**Issue by rbilski** [genome/civic-client#120] opened 2015-05-29 14:36 UTC
When I search for RUNX1 or FLI1 nothing comes up. Both of these genes show up with the evidence statements in the Browse feature but just not the search.

**Comment by malachig** [comment] 2015-05-29 15:38
The thinking was that this is probably due to caching (this was briefly mentioned in our last meeting).  I think Josh already fixed this here:

https://github.com/genome/civic-client/issues/106

I assume you are seeing this in the public version?  If so, the fix maybe just hasn't made it out there yet.

**Comment by jmcmichael** [comment] 2015-05-29 15:46
Nice catch. I wasn't able to reproduce your exact bug[1], but when I run the latest civic-server w/ the latest db import, RUNX1 doesn't show up for me in either location. 

Anyway, Looked into this and wasn't sure what was going on so I asked Adam. Quicksearch and Browse use the typeahead_results and /variants endpoints, respectively. If a gene has no variants defined (as RUNX1), then it won't show up in either location. So this is expected, if a bit unintuitive, behavior. 

[1] I couldn't find FLI1 anywhere, not even using admin search - is it included in the latest spreadsheet?

**Comment by jmcmichael** [comment] 2015-05-29 15:48
I don't think this has to do with caching, I verified that the server isn't returning RUNX1 from queries to the search APIs.

**Comment by malachig** [comment] 2015-05-29 16:02
Ok, thanks for the explanation.  FLI1 was added through the public instance as a test, so it isn't in the latest spreadsheet.

**Comment by jmcmichael** [comment] 2015-05-29 16:38
Cool, I'll go ahead and close this.

**Comment by kkrysiak** [comment] 2015-06-29 21:54
MGMT isn’t in quick browse but shows if you search using the "Browse by Gene" or "Browse by Variant" pages. It does have evidence items that are derived from the google spreadsheet. It does not, however, have a gene summary in either location. I'm not sure what is causing this behavior.

**Comment by jmcmichael** [comment] 2015-08-04 21:31
These differing search results are a server issue, see genome/civic-server#81 for more details.

**Closed by jmcmichael** 2015-08-04 21:31 UTC
