### ISSUE TITLE
Adding more information to the Drug column

### ISSUE THREAD

**Issue by nspies13** [genome/civic-client#36] opened 2015-02-21 01:28 UTC
In order to display type, direction and significance in the evidence table, it may work to color-code the drug column. 

Sensitvity could cause the drug text to be green, resistance red. 

Statements without drugs can print evidence type, with Diagnostic in Blue and Prognostic in Purple. 

Then the Supports/Refutes could be represented as an arrow?? I don't know if I like this.

**Comment by jmcmichael** [comment] 2015-02-24 16:12
Anything to increase the amount of horizontal space on those datagrids will be great to add, and something like this will probably work - but I want to avoid having to show a key to decipher special color/symbol meanings in the datagrid. One option would be to have a 'key' button that pops up a small table showing the color/symbol and its meaning.

**Comment by obigriffith** [comment] 2015-02-24 16:45
I like the pop-up key idea. Or, is it possible that mouse-over text would be enough to define symbols and abbreviations?

**Comment by malachig** [comment] 2015-02-24 16:58
I think this issue is basically a duplicate of one I already opened: #22 

I think all options are definitely on the table at this point.  The motivation is that currently you really have to click through each evidence statement to get the basic categories for each.  And these are fundamental to understanding what is going on.  It would be awesome if somehow we could represent type, direction and significance values in addition to what we have already.  But somehow without it becoming overwhelming or squishing the existing text too much...  I think we are already really pushing the use of existing horizontal space.  So adding three new things would probably have to be done in a very compact fashion.  With color coding, or symbols, or some combination of these maybe?  Right now the 'Level' column takes up a lot of space.  The 'Rating' column also could be squished down to just the width of 5 stars.  Maybe that would leave enough space for another column(s) that somehow encoded: type, direction and significance.

I like the idea of having a hover explanation for all of this.  A separate pop-up legend would also be great because is lays out the scheme all in one place and that can be helpful.

Ron Bose, raised the concern that having symbols/color coding makes the view feel too complicated or busy.  But I'm not sure how we can get around this.

**Comment by jmcmichael** [comment] 2015-09-01 19:54
Most of the concerns in this issue have been solved w/ the new evidence grid layout.

**Closed by jmcmichael** 2015-09-01 19:54 UTC
Labels: enhancement

**Comment by malachig** [comment] 2015-09-01 20:47
Agreed, this turned out great!
