### ISSUE TITLE
Advanced search for status is rejected doesn't appear to work.

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#362] opened 2016-03-04 20:37 UTC
I'm guessing this has something to do with the default behavior of hiding rejected evidence items but nothing happens when I try to search for them.

**Comment by obigriffith** [comment] 2016-03-04 21:14
Yeah. I noticed this too. I can still filter down to just rejected evidence items in the admin interface. But, on the public site, searching for "status is rejected" doesn't respond as expected.

**Comment by jmcmichael** [comment] 2016-03-04 21:23
The live server is returning a 500 error from searches for Rejected status. However, I'm unable to reproduce this on the latest server/client master - the search works fine.

**Comment by acoffman** [comment] 2016-03-04 21:57
So, it looks like this is only tangentially related to the advanced search. Here's what's happened:

* Evidence Item 1126 was submitted with description: `In 31enzalutamide-treated and 31 abiraterone-treated patients, detectable levels of AR-V7 was associated with resistance in these patients with castration resistant prostate cancer.`

* This submission caused the creation of a new variant: `SPLICE VARIANT 7`

* This evidence item was rejected

* Someone saw that this Variant had zero accepted evidence items and deleted it.

* Now we have an evidence item that points to a variant which has been (soft) deleted.

Basically its breaking when it tries to traverse the evidence item -> variant -> gene relationship to create the links needed for navigation because the variant has been deleted.

What I would recommend is to disallow the deletion of variants that have any evidence items at all (even if they're all rejected) and then once we ship genome/civic-client#328 (should be the next release) those variants will just not display by default in the side navigation. The downside of this is the case where this is the only variant for a gene.

Another possible solution would be cascading deletion of a variant to the corresponding evidence items which would be easy but have the effect of "hiding" the rejected evidence item which may not be desirable?

For the time being I've soft-deleted the evidence item so that search is working again, and I can implement whatever longer term solution makes sense to you guys!

**Comment by jmcmichael** [comment] 2016-03-09 23:58
Sounds like this issue has been fixed, closing.

**Closed by jmcmichael** 2016-03-09 23:58 UTC
