### ISSUE TITLE
Links to Data Releases broken?

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#99] opened 2015-05-21 03:59 UTC
From the public site I was not able to get the Data Releases URLs to work:

https://civic.genome.wustl.edu/#/releases

e.g. 
https://civic.genome.wustl.edu:3000/downloads/nightly/GeneSummaries.tsv
https://civic.genome.wustl.edu:3000/downloads/01-May-2015/GeneSummaries.tsv

**Comment by acoffman** [comment] 2015-05-21 15:11
I think this is a dupe of #97

**Closed by acoffman** 2015-05-21 15:11 UTC
Labels: bug
