### ISSUE TITLE
Disappearing dropdowns in advanced search

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#1223] opened 2019-10-10 19:56 UTC
Problem series:
<img width="725" alt="Screen Shot 2019-10-10 at 2 32 32 PM" src="https://user-images.githubusercontent.com/8527125/66600368-fae6c800-eb6a-11e9-9031-9ef493232868.png">
<img width="857" alt="Screen Shot 2019-10-10 at 2 32 38 PM" src="https://user-images.githubusercontent.com/8527125/66600379-fe7a4f00-eb6a-11e9-9dbd-716540a0dc1d.png">
<img width="731" alt="Screen Shot 2019-10-10 at 2 32 44 PM" src="https://user-images.githubusercontent.com/8527125/66601543-cb858a80-eb6d-11e9-8939-2f05af8cfb80.png">
<img width="794" alt="Screen Shot 2019-10-10 at 2 32 52 PM" src="https://user-images.githubusercontent.com/8527125/66601553-cfb1a800-eb6d-11e9-859d-42ca6bc53e8f.png">

It should look like this:
<img width="923" alt="Screen Shot 2019-10-10 at 2 55 48 PM" src="https://user-images.githubusercontent.com/8527125/66601665-11dae980-eb6e-11e9-8448-9072dbeb9d47.png">

**Comment by jmcmichael** [comment] 2019-10-14 15:25
This is actually a duplicate of #994, which I discovered when it popped up in a google search result for that included the error and other associated keywords. I dove under the hood for a couple hours on Friday but wasn't able to make much headway beyond where I'd gotten last year. Over the weekend I thought of some new avenues of attack to see what's going on but given that this seems like an edge case(?), and can be worked around by deleting the condition and adding a replacement condition, I think I'll de-prioritize this in my todos until I get some time to take a fresh look.

**Comment by susannasiebert** [comment] 2020-01-08 14:30
Since this is a duplicate of another issue I vote for closing it.

**Closed as completed** 2020-02-20 20:06 UTC
Labels: bug
