### ISSUE TITLE
alias list in MyGeneInfo popup shown as JSON array

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#1321] opened 2020-01-30 21:00 UTC
<img width="935" alt="Screenshot 2020-01-30 14 59 13" src="https://user-images.githubusercontent.com/132909/73490011-40750e00-4371-11ea-80c4-8ca4a02dd11c.png">

Should be displayed as a list.

**Comment by susannasiebert** [comment] 2020-02-27 19:30
Closing because duplicate of 1166

**Closed as completed by susannasiebert** 2020-02-27 19:30 UTC
Labels: bug, duplicate
