### ISSUE TITLE
Unable to type gene manually in add evidence item field

### ISSUE THREAD

**Issue by zlskidmore** [genome/civic-client#450] opened 2016-06-23 21:41 UTC
Minor issue, however when adding an evidence item it is not possible to just type in EGFR within the gene field, for example, you cant type in EGFR and move down to another field you actually have to click on EGFR from the drop down in order to submit an EID.

**Comment by jmcmichael** [comment] 2016-06-24 15:26
I'm upgrading many of the components, including typeaheads, so I'll take a look at this.

However, it's likely that we will have to have some kind of interaction with the typeahead since we are only allowing valid entrez gene names. The form element has to check for valid names from the server, which it then populates itself via a user (or default) choice on the typeahead menu. So the user will likely either have to choose an item by hitting return or clicking, or have the control select the currently highlighted value if they move to a different form element by clicking or pressing tab.

**Comment by jmcmichael** [comment] 2016-09-29 15:35
Closing, as this is expected behavior from the typeahead control when field contents are restricted to items provided by the typeahead.

**Closed by jmcmichael** 2016-09-29 15:35 UTC
Labels: high priority
