### ISSUE TITLE
Unable to mark notifications as read.

### ISSUE THREAD

**Issue by jsaliba10** [genome/civic-client#1430] opened 2020-07-16 05:43 UTC
When on the subscribed events notifications page, clicking on "mark as read" or "mark as unread" does not result in a change of status for the notification. 
<img width="1516" alt="Screen Shot 2020-07-16 at 12 43 15 AM" src="https://user-images.githubusercontent.com/59739804/87631653-644cc600-c6fd-11ea-9e91-d7b34386101d.png">

**Comment by acoffman** [comment] 2020-07-16 13:31
Huh, I can't reproduce this with my own notifications. Is it all of your notifications or particular ones where you're seeing this?

**Comment by jsaliba10** [comment] 2020-07-16 16:26
Seems to be all of them. I restarted my computer, cleared cacher, forced refresh, tried different browsers.  None of that seemed to work. 
I am going to slack you a screen recording. When I click "mark read" the blue loading bar runs through at the top.

**Comment by acoffman** [comment] 2020-08-12 16:38
I am suspecting that this is also a result of/will be fixed by: griffithlab/civic-server#634. I'll test it out once we roll that PR out to staging to confirm.

**Closed as completed by acoffman** 2020-08-12 16:38 UTC
