### ISSUE TITLE
Unable to accept evidence items. 

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#320] opened 2016-01-15 05:37 UTC
I am currently unable to accept submitted evidence items. At first I thought it was a refresh error on my phone so I moved on to a few others. This one I have repeatedly attempted.

https://civic.genome.wustl.edu/#/events/genes/20/summary/variants/232/summary/evidence/760/summary#evidence

I have tried accepting this on my phone and on my laptop (firefox). I have also tried signing out and restarting my browser. I've confirmed that my user role is still admin. I can also still submit and accept changes. My last successfully accepted evidence statement was 16 days ago.

**Comment by kkrysiak** [comment] 2016-01-15 05:54
On further thought, this may have been the problem that led to an applied change prior to an evidence statement being accepted and then left in limbo 15 days ago.

https://civic.genome.wustl.edu/#/events/genes/37/summary/variants/212/summary/evidence/756/talk/revisions/list/591/summary#evidence

This is a shot in the dark but my user accounts were merged in one of our meetings a few weeks ago (not sure if it would be 2 or 3 weeks though) and perhaps did something funny to my account.

**Comment by acoffman** [comment] 2016-01-15 15:35
Hrm, that's weird. I'll take a look at this today!

**Comment by malachig** [comment] 2016-01-16 05:35
Hmm, it seems that I also can not accepted evidence items right now.
```
https://civic.genome.wustl.edu/api/evidence_items/906/accept 500 (Internal Server Error)
Ooops! There was an error accepting this evidence item.

```

**Comment by malachig** [comment] 2016-01-16 05:38
I also get an error if I try to accept this item in the admin interface. I was attempting to accept this one:
https://civic.genome.wustl.edu/#/events/genes/45/summary/variants/369/summary/evidence/906/summary#evidence

**Comment by malachig** [comment] 2016-01-19 16:46
@obigriffith also confirmed that he is unable to accept evidence items.

**Comment by malachig** [comment] 2016-01-19 17:00
@acoffman a bit more detail on this.  This issue seems to be confined to accepting new evidence items only.  I am able to accept revisions to existing evidence items and variants.  Did so for a few suggestions from multiple different users.  New evidence items can be submitted as well.

**Comment by acoffman** [comment] 2016-01-19 17:30
@malachig Gotcha, thanks for updates and clarifications. This sounds like a fairly high priority issue. I'll get right on it today!

**Comment by acoffman** [comment] 2016-01-20 19:38
@malachig @kkrysiak This issue should now be resolved in production! You should be able to accept these evidence items.

**Closed by acoffman** 2016-01-20 19:38 UTC
